### ISSUE TITLE
Resumes

### ISSUE THREAD

**Issue by mickdelaney** [codecapital/CodeCapital.Bullhorn#7]
First of all thanks for the great lib !!! 
I've just started creating one myself, but perhaps i'll contribute now to yours.

one scenario for me is trying to download Resumes for Candidates, but i dont seem to be able to determine what files are Resumes vs anything else, e.g. Contracts, Certificates etc.

Is that something you've come across ?

**Comment by VaclavElias** [comment]
You are welcome 😃. There could be much more done on this library and I would like to refactor it and clean up once I have got some time to do it...

I think **type** returns the file type but it might vary from client to client

entity/Candidate/123456/fileAttachments?fields=name,**type**,id,fileType,externalID,fileExtension,fileSize,directory,contentType,contentSubType,distribution

When I tested this query above, I could see different **type**s showing up, same as individual Bullhorn clients have in their Bullhorn UI.

http://bullhorn.github.io/rest-api-docs/entityref.html#entity-fileattachment
http://bullhorn.github.io/rest-api-docs/index.html#get-entity-entitytype-entityid-fileattachments

**Comment by mickdelaney** [comment]
Thanks, i also noticed the 'meta' URLs return the schema from the actual api, which i guess is the way to go. rather than the Docs 

e.g. https://123.bullhornstaffing.com/rest-services/123/meta/Candidate?fields=*&meta=full&BhRestToken=123
